export default [
    {
        chapter: 1,
        name: "Topological Spaces and Continuous Functions",
        statements: [
            {
                id: "1",
                type: "definition",
                content: "Let $X$ be a set. A collection $\\mathcal{T}\\subseteq\\mathcal{P}(X)$ is called a topology on $X$ if $\\mathcal{T}$ satisfies the following properties $\\\\ \\text{1. }$ $\\varnothing\\in\\mathcal{T}$ and $X\\in\\mathcal{T}.$ $\\\\ \\text{2. }$ $\\mathcal{T}$ is closed under finite intersections. That is, given an. $X$ is also called a $\\textbf{topological space}$. A subset $U$ of $X$ that it in $\\mathcal{T}$ is called an $\\textbf{open set}$. A subset $V$ of $V$ is $\\textbf{closed}$ if $X\\setminus V$ is open.",
                short: "A collection $\\mathcal{T}\\subseteq\\mathcal{P}(X)$ is called a topology on $X$ if it contains $\\varnothing$ and $X$, and is closed under unions and finite intersections. $X$ is also called a $\\textbf{topological space}$. Any $U\\in\\mathcal{T}$ is called an $\\textbf{open set}$. Any $V$ is closed $\\textbf{closed}$ if $X\\setminus V$ is open.",
                depending: []
            },
            {
                id: "2",
                type: "definition",
                content: "",
                short: "For each $x\\in X$, $U\\in\\mathcal{T}$ is a $\\textbf{neighborhood}$ of $x$ if $x\\in U$.",
                depending: []
            },
            {
                id: "2",
                type: "definition",
                content: "",
                short: "Given $A\\subseteq X$. $\\\\\\textbf{1.}$ The $\\textbf{closure}$ of $A$ is $\\overline{A} = \\bigcap\\{B\\subseteq X\\,|\\, B\\supseteq A, B \\text{ is closed}\\}$.  $\\\\\\textbf{2.}$ The $\\textbf{interior}$ of $A$ is $\\overset{\\circ}{A} = \\bigcup\\{C\\subseteq X\\,|\\, C\\subseteq A, C \\text{ is open}\\}$. $\\\\\\textbf{3.}$ The $\\textbf{exterior}$ of $A$ is $\\mathrm{ext}\\,A = X\\setminus A$. $\\\\\\textbf{4.}$ The $\\textbf{boundary}$ of $A$ is $\\partial A = X\\setminus(\\overset{\\circ}{A}\\cup \\mathrm{ext}\\,A)$.",
                depending: []
            },
            {
                id: "2",
                type: "definition",
                content: "A collection $\\mathcal{B}\\subseteq\\mathcal{P}(X)$ is called a topological basis if $\\\\ \\textbf{1. }$ $X = \\bigcup \\mathcal{B}$. $\\\\\\textbf{2. }$  $\\forall B_1,B_2\\in \\mathcal{B},\\, \\forall x \\in B_1\\cap B_2,\\,\\exists B_3\\in\\mathcal{B}$ such that  $x\\in B_3\\subseteq B_1\\cap B_2$.",
                depending: []
            },

            {
                id: "1.1",
                name: "Find topology from basis",
                content: "",
                type: "theorem",
                short: "The set $\\\\\\begin{aligned} \\mathcal{T}_\\mathcal{B} &= \\{U \\subseteq X \\,|\\, \\forall x\\in U,\\,\\exists B\\in\\mathcal{B}: x\\in B\\subseteq U \\} \\\\ &= \\left\\{\\bigcup\\mathcal{C} \\,|\\, \\mathcal{C}\\subseteq\\mathcal{B} \\right\\} \\end{aligned}\\\\$ is a topology called the topology generated by $\\mathcal{B}$.",
                depending: []
            },
            {
                id: "1.2",
                name: "Find basis from topology",
                content: "",
                type: "theorem",
                short: "$\\mathcal{C}\\in\\mathcal{P}(X)$ is a topological basis of $X$ if $\\forall x\\in U \\in\\mathcal{T},\\,\\exists C\\in\\mathcal{C}$ such that $x\\in C \\subset U$.",
                depending: []
            },
            {
                id: "1.3",
                name: "Compare two topologies",
                content: "Let topologies $\\mathcal{T}$ and $\\mathcal{T'}$ having bases $\\mathcal{B}$ and $\\mathcal{B}'$, respectively. Then $\\mathcal{T}\\subseteq\\mathcal{T}'$ if and only if $\\forall x\\in B\\in\\mathcal{B},\\exists B'\\in\\mathcal{B}' : x\\in B'\\subseteq B$.",
                type: "theorem",
                short: "$\\\\\\mathcal{T}_{\\mathcal{B}_1}\\subseteq\\mathcal{T}_{\\mathcal{B}_2} \\Leftrightarrow \\forall x\\in B_1\\in\\mathcal{B}_1,\\exists B_2\\in\\mathcal{B}_2 : x\\in B_2\\subseteq B_1$.",
                depending: []
            },
            {
                id: "3",
                name: "",
                type: "definition",
                content: "An $\\textbf{order topology}$ is whose basis contains elements of the form $(a,b), [a_0,b), (a,b_0]$, where $a,b\\in X$, $a_0$ is the smallest element if any, $b_0$ is the largest element if any.",
                type: "definition",
                depending: []
            },
        ]
    }
]